apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ultimate-devops-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yathampragathi25-collab/ultimate-devops-project.git
    targetRevision: main
    path: kubernetes

    directory:
      recurse: true
      exclude: '{complete-deploy.yaml,frontendproxy/ingress.yaml}'

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
